### ISSUE TITLE
Mod fails to start. 'RegisterTypes' is failing IL2CPP

### ISSUE THREAD

**Issue by wund3rcr4zy** [wund3rcr4zy/by-the-book#6]
**Mod Version (Required)**
0.2.0

**Shadows of Doubt Game Version (Required)**
Experimental and main branch. Latest version as of 10/13/2024

**Describe the bug (Required)**
```
[Error  :   BepInEx] Error loading [ByTheBook 0.2.1]: System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.FindGetTypeInfoFromTypeDefinitionIndex(Boolean forceICallMethod) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 269
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.Setup() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 68
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 188
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 147
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp[T]() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 142
   at ByTheBook.ByTheBookPlugin.RegisterTypes() in C:\Users\Bobby\Desktop\Game_Modding\Shadows_Of_Doubt\ByTheBook\ByTheBookPlugin.cs:line 47
   at ByTheBook.ByTheBookPlugin.Load() in C:\Users\Bobby\Desktop\Game_Modding\Shadows_Of_Doubt\ByTheBook\ByTheBookPlugin.cs:line 33
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 134
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 411
```
**To Reproduce (Optional)**
Start with mod enabled on latest/experimental

**Comment by Khundiann** [comment]
fixed in v0.2.1
